name: 'Install Plumed'
description: 'Installs plumed from https://github.com/plumed/plumed2'
inputs:
  repository:
    description: 'The url of the Plumed repository'
    required: false
    default: 'https://github.com/plumed/plumed2.git'
  suffix:
    description: 'Suffix for the program name'
    required: false
    default: ''
  version:
    description: 'The version of plumed to install (default to master)'
    required: false
    default: 'master'
  program_name:
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Set up environment
      shell: bash
      run: |
        sudo apt update
        sudo apt install mpi-default-bin mpi-default-dev
        sudo apt install libfftw3-dev gsl-bin libgsl0-dev libboost-serialization-dev
        sudo apt install ccache
        sudo apt-get update
    - name: Install plumed
      run: $GITHUB_ACTION_PATH/install-plumed.sh
      shell: bash
      env:
        SUFFIX: ${{ inputs.suffix }}
        VERSION: ${{ inputs.version }}
        PROGRAM_NAME: ${{ inputs.program_name }}
        REPO: ${{ inputs.repository }}