name: 'Install Plumed'
description: 'Installs plumed from https://github.com/plumed/plumed2'
inputs:
  repository:
    description: 'The url of the Plumed repository'
    required: false
    default: 'https://github.com/plumed/plumed2.git'
  version:
    description: 'The version of plumed to install (default to master)'
    required: false
    default: ''
  suffix:
    description: 'Suffix for the program name'
    required: false
    default: ''
  prefix:
    description: 'The installation prefix'
    required: false
    default: '~/opt'
  extra_options:
    description: 'Extra options for installing plumed'
    required: false
    default: '--enable-boost_serialization --enable-fftw --enable-libtorch'
  modules:
    description: 'List of modules to install, or "all"'
    required: false
    default: 'all'
  CC:
    description: 'C compiler'
    required: false
    default: 'gcc'
  CXX:
    description: 'C++ compiler'
    required: false
    default: 'g++'
  dependency_path:
    description: 'Path where to store "extradeps$version.json"'
    required: false
    default: ''
outputs:
  plumed_prefx:
    description: "Plumed executable path"
    value: ${{ steps.installation.outputs.plumed_path }}
  depencies:
    description: "Plumed dependency json file"
    value: ${{ steps.installation.outputs.depencies }}
runs:
  using: "composite"
  steps:
    # - name: Set up environment
    #   shell: bash
    #   run: |
    #     sudo apt update
    #     sudo apt install mpi-default-bin mpi-default-dev
    #     sudo apt install libfftw3-dev gsl-bin libgsl0-dev libboost-serialization-dev
    #     sudo apt install ccache
    #     sudo apt-get update
    - name: Install plumed
      id: installation
      run: $GITHUB_ACTION_PATH/install-plumed.sh
      shell: bash
      env:
        REPO: ${{ inputs.repository }}
        VERSION: ${{ inputs.version }}
        SUFFIX: ${{ inputs.suffix }}
        PREFIX: ${{ inputs.prefix }}
        EXTRA_OPTIONS: ${{ inputs.extra_options }}
        MODULES: ${{ inputs.modules }}
        CC: ${{ inputs.CC }}
        CXX: ${{ inputs.CXX }}
        DEPPATH: ${{ inputs.dependency_path }}
