name: Test

on: [push, pull_request]

jobs:
  
  test:
    # strategy:
    #   matrix:
    runs-on: ubuntu-latest

    steps:
    - name : install plumed
      uses: Iximiel/install-plumed@main
      with:
        modules: 'reset'
        dependency_path: '$GITHUB_WORKSPACE/_data/'
      id: plumed
    - name: run plumed
      run: |
        echo ${{ steps.plumed.outputs.path }}
        head ${{ steps.plumed.outputs.dependency_path }}
        plumed --version
        
  test_Stable:
    # strategy:
    #   matrix:
    runs-on: ubuntu-latest

    steps:
    - uses: Iximiel/install-plumed@v1
    - name: run plumed
      run: |
        plumed --version
    